# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bulkk-Import"
client_id = "e8713189b5202bee92713ccf9fdf30a7"
application_url = "https://alignment-kits-dynamics-survive.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://alignment-kits-dynamics-survive.trycloudflare.com/auth/callback",
  "https://alignment-kits-dynamics-survive.trycloudflare.com/auth/shopify/callback",
  "https://alignment-kits-dynamics-survive.trycloudflare.com/api/auth/callback",
  "https://alignment-kits-dynamics-survive.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alphaaastore.myshopify.com"
