# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bulk-Uploads"
client_id = "33baef35c56a1dc85acd506f172ca75f"
application_url = "https://soc-chem-tiffany-grad.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_customers,read_assigned_fulfillment_orders,read_product_listings,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://soc-chem-tiffany-grad.trycloudflare.com/auth/callback",
  "https://soc-chem-tiffany-grad.trycloudflare.com/auth/shopify/callback",
  "https://soc-chem-tiffany-grad.trycloudflare.com/api/auth/callback",
  "https://soc-chem-tiffany-grad.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alphaaastore.myshopify.com"
