# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bulk-upload"
client_id = "66ed47b800f77d9acaabf8aa937b2c3e"
application_url = "https://d552-49-36-80-71.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://d552-49-36-80-71.ngrok-free.app/auth/callback",
  "https://d552-49-36-80-71.ngrok-free.app/auth/shopify/callback",
  "https://d552-49-36-80-71.ngrok-free.app/api/auth/callback",
  "https://d552-49-36-80-71.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alphaaastore.myshopify.com"
