# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bulkk-Import"
client_id = "e8713189b5202bee92713ccf9fdf30a7"
application_url = "https://weblog-cancer-question-applies.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://weblog-cancer-question-applies.trycloudflare.com/auth/callback",
  "https://weblog-cancer-question-applies.trycloudflare.com/auth/shopify/callback",
  "https://weblog-cancer-question-applies.trycloudflare.com/api/auth/callback",
  "https://weblog-cancer-question-applies.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alphaaastore.myshopify.com"
