# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bulk-Import"
client_id = "d5c1a2f652f4bc61d62143af2e60bb47"
application_url = "https://warnings-frederick-varied-op.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"

[auth]
redirect_urls = [
  "https://warnings-frederick-varied-op.trycloudflare.com/auth/callback",
  "https://warnings-frederick-varied-op.trycloudflare.com/auth/shopify/callback",
  "https://warnings-frederick-varied-op.trycloudflare.com/api/auth/callback",
  "https://warnings-frederick-varied-op.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alphaaastore.myshopify.com"
